# Generated by Django 4.2.28 on 2026-03-13 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='gender')),
                ('academic_level', models.CharField(choices=[('P.1', 'Primary 1'), ('P.2', 'Primary 2'), ('P.3', 'Primary 3'), ('P.4', 'Primary 4'), ('P.5', 'Primary 5')], max_length=10, verbose_name='Current Academic Level')),
                ('enrollment_status', models.CharField(choices=[('actiive', 'Active'), ('dismissed', 'Dismissed'), ('graduated', 'Graduated'), ('transfered', 'Transferred')], max_length=20, verbose_name='Enrollment_status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
